### ISSUE TITLE
Tab Indicator Not showing when i change the tabbackground color

### ISSUE THREAD

**Issue by bpr10** [astuetz/PagerSlidingTabStrip#151]
When i set the tab background to white the indicator is not showing . and when i do not mak enay changes to the tab background then a underline same as the indicator color comes which does nt go even if a set underline color to transparent or make underline height to 0

**Comment by ekilah** [comment]
depends on the color you want to use, but if for whatever reason you don't want to an active fork like @biftekman posted, you can always use a semi-transparent background color.

**Comment by uberchilly** [comment]
You can use tabs.setBackgroundColor(Color.parseColor("#3D3D3D"));
and it will work with underline and indicator but selector for each tab will be ugly and default bluish color. Fix for this would be to set selector as 
app1:pstsTabBackground="@drawable/tabs_background" 
with transparent main color and semitransparen pressed color:
