### ISSUE TITLE
Failed to find:com.com.astuetz:pagerslidingtabstrip:1.0.1

### ISSUE THREAD

**Issue by NancyZY** [astuetz/PagerSlidingTabStrip#173]
I'm prepared to import pagerslidingtabstrip,but I got some trouble in  this process. First,I add the dependency in my build.gradle.,like belows code: compile 'com.astuetz:pagerslidingtabstrip:1.0.1' ,and the android studio imply "Failed to find:com.com.astuetz:pagerslidingtabstrip:1.0.1" .Then, I changed the ways that download your .zip file and then unzip ,next, I import its  library folder to my project library,and change the correct version in build.gradle in your library files .the same error was occoured.I'm use the I am using Android Studio 1.0.2 .thanks for your help in advance!

**Comment by hangox** [comment]
"Failed to find:com.com.astuetz:pagerslidingtabstrip:1.0.1" 
your problem is double "com",  can your see that???

if you used library 
change your dependencies like this

```java
   dependencies {
        compile project(':library name')
    }
```

**Comment by NancyZY** [comment]
Hi,I knew the reason why I didn't achieve it before.just because I forgot to turn on the  button which could allow the gradle pull the resource from the site. I'm too careless.and can you help me to solve other problem in this proccess. I want to make PagerSlidingTabStrip have three tabs.the function works perfect,but the layout didn't show friendly.I will send the picture to let you more understand what I want to express.(PS: I tried to do this ,set the property  in PagerSlidingTabStrip :pagerSlidingTabStrip.setTabPaddingLeftRight(20).)
![Uploading device-2015-01-09-212041.png . . .]()

**Comment by NancyZY** [comment]
Hi,I knew the reason why I didn't achieve it before.just because I forgot to turn on the  button which could allow the gradle pull the resource from the site. I'm too careless.and can you help me to solve other problem in this proccess. I want to make PagerSlidingTabStrip have three tabs.the function works perfect,but the layout didn't show friendly.I will send the picture to let you more understand what I want to express.(PS: I tried to do this ,set the property  in PagerSlidingTabStrip :pagerSlidingTabStrip.setTabPaddingLeftRight(20).)
![device-2015-01-09-212041](https://cloud.githubusercontent.com/assets/9473445/5690432/f0008984-98c3-11e4-96b4-01ab3731b5af.png)

**Comment by hangox** [comment]
you speak chinese??this library cannot do it like that.you can use linearlayout do it
