### ISSUE TITLE
Am I supposed to use the new Toolbar object for tabs now?

### ISSUE THREAD

**Issue by ewhite-dev** [astuetz/PagerSlidingTabStrip#176]
For tabs right under the actionbar, should I be using the new Toolbar object instead, or are we still intended to use ViewPager with the PagerSlidingTabStrip (or other similar library)?

**Comment by ataulm** [comment]
Still use the ViewPager. There's no sliding tab strip functionally afforded into the Toolbar view.

**Comment by ewhite-dev** [comment]
@ataulm that's true, although I switched to SlidingTabLayout object that Google released with material design and the compabitility pack updates. It seems inspired by PagerSlidingTabStrip and has many of the same methods

**Comment by ataulm** [comment]
Whether you use the SlidingTabLayout or this library, the Toolbar is a separate view, unrelated to the tabs (if that answers your question, you can close this issue).

As an aside, so far I'm preferring this one (to SlidingTabLayout) because it's keyboard/trackball accessible by default.
