### ISSUE TITLE
tabs.setOnLongClickListener

### ISSUE THREAD

**Issue by arashmidos** [astuetz/PagerSlidingTabStrip#207]
I want to handle long click on my tabs to popup a menu for Editing tab's name or Deleting the entire tab hierarchy.But it doesn't work. 

tabsStrip.setOnLongClickListener( new View.OnLongClickListener()
        {
            @Override
            public boolean onLongClick(View v)
            {
                Log.d(TAG,"something");
                return false;
            }
        });

**Comment by theBlbDan** [comment]
What really needs to happen is PagerSlidingTabStrip needs to provide a OnLongClickListener.  As can bee seen in PagerSlidingTabStrip#addTab()
```java
private void addTab(final int position, View tab) {
	tab.setFocusable(true);
	tab.setOnClickListener(new OnClickListener() {
		@Override
		public void onClick(View v) {
			pager.setCurrentItem(position);
		}
	});

	tab.setPadding(tabPadding, 0, tabPadding, 0);
	tabsContainer.addView(tab, position, shouldExpand ? expandedTabLayoutParams : defaultTabLayoutParams);
}
```
the TextView isn't set up to respond.  A hacky work around:
```java
PagerSlidingTabStrip tabs = (PagerSlidingTabStrip) v.findViewById(R.id.tabs);
tabs.setShouldExpand(true);
tabs.setViewPager(mViewPager);
ViewGroup tabVG = (ViewGroup) tabs.getChildAt(0);
int children = tabVG.getChildCount();
for(int ii=0;ii<children;ii++) {
	View vv = tabVG.getChildAt(ii);
	vv.setLongClickable(true);
	vv.setOnLongClickListener(new View.OnLongClickListener() {
		@Override
		public boolean onLongClick(View v) {
			toastMessageLong("We just long clicked");
			return false;
		}			
	});
}
```

**Comment by arashmidos** [comment]
Thanks. In this way I can have multicolored tabs easily.
