### ISSUE TITLE
How to make tabs fill width of the screen?

### ISSUE THREAD

**Issue by Zapnologica** [astuetz/PagerSlidingTabStrip#212]
I only have three tabs on my screen, so its not enough content to fill the screen.

But the tab slider does not take up all of the screen space. See below:
---- (added instead of free space, as formatting was effected)
|-------------------------------------------|
| Tab1 | Tab 2 | Tab 3  -------------|
|-------------------------------------------|

I want something like this:

|-------------------------------------------|
|---Tab1---|---Tab 2 ---|---Tab 3---|
|-------------------------------------------|

**Comment by theBlbDan** [comment]
I don't recall where I found this, possibly eclipse javadoc, but the solution is setShouldExpand(true):
```java
// Bind the tabs to the ViewPager
PagerSlidingTabStrip tabs = (PagerSlidingTabStrip) v.findViewById(R.id.tabs);
tabs.setShouldExpand(true);
tabs.setViewPager(mViewPager);
```

**Comment by Zapnologica** [comment]
That did the job. Thank you so much. It looks way better now.
