### ISSUE TITLE
How to set the select tab text color?

### ISSUE THREAD

**Issue by IsSwm** [astuetz/PagerSlidingTabStrip#303]
How to set the select tab text color?

**Comment by TechnologyMaster** [comment]
@IsSwm use this property in xml file to set select tab text color.

<com.astuetz.PagerSlidingTabStrip
 android:id="@+id/tabs"
app:pstsActivateTextColor="@color/white"
 app:pstsDeactivateTextColor="@color/white"
/>

**Comment by IsSwm** [comment]
Thanks.

**Comment by zhengmingliang** [comment]
![](http://ww1.sinaimg.cn/large/e6112e40ly1fee902h4yjj20fy0i140g.jpg)

It didn't work,I found that the library did not have `pstsActivateTextColor ` and `pstsDeactivateTextColor` attributes

**Comment by IsSwm** [comment]
我刚才查看了一下的确没有呢，可能他还并没有更新版本吧。

**Comment by zhengmingliang** [comment]
@IsSwm @astuetz @TechnologyMaster 好吧，先谢谢了，我先自己添加上，过些日子再更新下就行

**Comment by TechnologyMaster** [comment]
@zhengmingliang  @IsSwm  I have made some changes in the library. and if possible then talk in English , so i can understand.

**Comment by IsSwm** [comment]
Ok,Thanks.

**Comment by zhengmingliang** [comment]
![image](https://cloud.githubusercontent.com/assets/16442564/24796101/40794c1e-1bbe-11e7-94a2-e12a9eb880b3.png)
Please look at this picture

**Comment by zhengmingliang** [comment]
![](http://ww1.sinaimg.cn/large/e6112e40ly1feeaa6tzaqj20ll0m040z.jpg)
@TechnologyMaster   please look at this picture,I add the code ,but it didn't work:
```xml
app:pstsActivateTextColor="@color/white"
app:pstsDeactivateTextColor="@color/black"
```

**Comment by TechnologyMaster** [comment]
wait I will give you code . can you wait ? @zhengmingliang

**Comment by zhengmingliang** [comment]
sure,thanks a lot @TechnologyMaster
