### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by austynmahoney** [astuetz/PagerSlidingTabStrip#77]
The owner has not contributed anything on Github for almost 3 months. There are over 40 issues currently open, with only a few with a response from the owner.

I am willing to create and maintain a new active fork of this if he does not respond within the next couple days.

This is an important piece of an application I am writing, so it has been necessary to cherry pick some of the proposed fixes from open PRs. There seems to be a lot of community around this project, but no contributor to merge that work. Let's help each other out and get all these fixes and improvements into a library.

**Comment by jpshelley** [comment]
@astuetz has put in great work, but if it wasn't going to be maintained it should have been turned into a gist since its so short. I can't even view all the forks from the web interface because there are so many.

**Comment by austynmahoney** [comment]
I'm still here. Contribute all you want to my fork. I will respond and merge if it meets the projects quality requirements.
