### ISSUE TITLE
How to change the tab title color?

### ISSUE THREAD

**Issue by HanderWei** [astuetz/PagerSlidingTabStrip#86]
Any help will be highly appreciate.

**Comment by rzeh4n** [comment]
Version 1.0.1
The method is called setTextColor(color), not setTextTabColor(color). 
Also I think this should be configurable in layout (pstsTabTextColor or something like that).

**Comment by uberchilly** [comment]
You can use tabs.setBackgroundColor(Color.parseColor("#3D3D3D"));
and it will work with underline and indicator but selector for each tab will be  ugly and default bluish color. Fix for this would be to set selector as 
app1:pstsTabBackground="@drawable/tabs_background" 
with transparent main color and semitransparen pressed color:

<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
<item android:drawable="@color/colorTabBarPressed" android:state_pressed="true"/>
<item android:drawable="@color/colorTabBarPressed" android:state_focused="true"/>
<item android:drawable="@android:color/transparent"/>
</selector>

**Comment by pixraider** [comment]
Guys, I've just add **android:textColor**
<pre><code>
 < style name="PagerSlidingTabStrip">
        < item name="android:background">?attr/colorPrimary< /item>
        < item name="android:textColor">@your/color< /item>
        < item name="pstsTextColorSelected">@android:color/white< /item>
        < item name="pstsIndicatorColor">@android:color/white< /item>
        < item name="pstsDividerColor">?attr/colorPrimary< /item>
        ...
< /style>
</code></pre>

It changes a title color. For change selected title color use **pstsTextColorSelected** accordingly
